import type { Lang } from "./translations";
import type { RuleSummary } from "../data/types";
import generated from "./generated/rules.json";

/**
 * A static, build-time snapshot of rules/*.yaml (generated by
 * `go run ./internal/correlate/gen`, kept fresh by
 * internal/correlate/rules_catalogue_test.go), used wherever there is no
 * live recorder to ask - demo mode and bundle mode never call `/v1/rules`
 * at all (`useRecord.ts`'s own doc comment: "Live source only").
 *
 * ADR 0004: "A build step generates desktop/src/i18n/generated/rules.json
 * from rules/*.yaml, so demo mode and bundle mode ... also render Arabic
 * rule text." A live recorder's own `/v1/rules` response always wins over
 * this snapshot when both are available (`findRule` below) - a live
 * connection can be pointed at a customized rules directory, and this
 * static file can only ever reflect what shipped with this build.
 */
const staticRules: Record<string, RuleSummary> = Object.fromEntries(
  (generated.rules as unknown as RuleSummary[]).map((r) => [r.id, r]),
);

export function getStaticRule(ruleId: string): RuleSummary | undefined {
  return staticRules[ruleId];
}

/** Prefers a live-fetched rule (fresher, and authoritative for what this
 *  specific recorder actually has loaded) over the static snapshot. */
export function findRule(ruleId: string, liveRules: RuleSummary[]): RuleSummary | undefined {
  return liveRules.find((r) => r.id === ruleId) ?? staticRules[ruleId];
}

/**
 * These three all take the already-known English text as `fallback` and
 * only ever use it as retrieved - never a current rule field standing in
 * for it. An incident's `title`/`advice`/a link's `why` are copied into
 * the incident at the moment it was built (`engine.go`'s `build()`) and
 * are the authoritative record of what was actually said; the rule
 * catalogue (live or static) is consulted only to find a *translation* of
 * that same text, never to silently replace it with whatever the rule
 * file says today (which, for an old bundle or an edited rule, can differ
 * from what actually fired).
 *
 * Absent translation (including always, for `lang === "en"`, since a rule
 * only ever carries translations *into* other languages) falls through to
 * `fallback` - the ADR's "unknown or newer key falls back to the
 * original, never blank" rule, applied per string rather than per rule.
 */
export function titleFor(rule: RuleSummary | undefined, lang: Lang, fallback: string): string {
  return rule?.i18n?.[lang]?.title ?? fallback;
}

export function adviceFor(rule: RuleSummary | undefined, lang: Lang, fallback: string): string {
  return rule?.i18n?.[lang]?.advice ?? fallback;
}

export function whyFor(
  rule: RuleSummary | undefined,
  clause: string | undefined,
  lang: Lang,
  fallback: string,
): string {
  if (!clause) return fallback;
  return rule?.i18n?.[lang]?.clauses?.[clause] ?? fallback;
}
